add install instructions
QEDjl-project/QEDevents.jl pull request #2
Opened 2023-06-19 12:18 UTC by SimeonEhrig

- We use a local registry. Therefore some extra steps are required beside the default installation commands.

2023-07-03 19:13 UTC, szabo137 requested changes
@SimeonEhrig

2023-07-03 19:13 UTC, szabo137 commented on README.md
> +# add general registration again, that it is still available beside the local QED registry
I suggest rephrasing: 

 add general registry again to have it join the local registry

2023-07-03 19:13 UTC, szabo137 commented on README.md
> +# add general registration again, that it is still available beside the local QED registry
I suggest rephrasing: 

add general registry again to have it join the local registry

2023-07-03 19:13 UTC, szabo137 commented on README.md
> +# add general registration again, that it is still available beside the local QED registry
@SimeonEhrig

2023-07-03 19:14 UTC, szabo137 commented on README.md
> +# add general registration again, that it is still available beside the local QED registry
@SimeonEhrig

2023-07-04 06:39 UTC, SimeonEhrig commented
@szabo137 ready to merge

2023-08-22 09:17 UTC, szabo137 approved these changes
Everything is ready to merge!

2023-08-22 09:17 UTC, merged